version: "3.9"

services:
  login:
    image: 'login:lastest'
    container_name: login
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - USER_DEV=tatho
      - PASS_DEV=12345678
    ports:
      - "2004:8080"
    networks:
      - spring-cloud-network


networks:
  spring-cloud-network:
    driver: bridge
